#ifndef ESTADOS_H_INCLUDED
#define ESTADOS_H_INCLUDED
#include <stdio.h>
#include <stdlib.h>

//SAIDAS
#define VELOCIDADE 0x10
#define DIRECAOMOTORDIR 0x20
#define DIRECAOMOTORESQ 0x40
#define BUZZER 0x80

enum Estados {INIT,COMECOUDIR,COMECOUESQ,UMPONTO,SEGUNDARODADADIR,SEGUNDARODADAESQ,DOISPONTOS,TERCEIRARODADADIR, TERCEIRARODADAESQ,PERDEU,GANHOU};

unsigned char estados(unsigned short entrada);

#endif // ESTADOS_H_INCLUDED
